### ISSUE TITLE
Error setting up Labeller, Invalid Token

### ISSUE THREAD

**Issue by RitualSSB** [aliceisjustplaying/labeler-starter-kit-bsky#2] opened 2024-11-14 17:18 UTC
Getting the following error, what am I screwing up? 
Error setting up labeler: XRPCError: InvalidToken > Token is invalid
    at XRPC.request (file:///tmp/bunx-1000-@skyware/labeler@latest/node_modules/@atcute/client/dist/rpc.js:82:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async plcSetupLabeler (file:///tmp/bunx-1000-@skyware/labeler@latest/node_modules/@skyware/labeler/dist/scripts/plc.js:55:19)
    at async file:///tmp/bunx-1000-@skyware/labeler@latest/node_modules/@skyware/labeler/dist/bin.js:42:31 {
  status: 400,
  kind: 'InvalidToken',
  description: 'Token is invalid',
  headers: {
    'access-control-allow-origin': '*',
    'cache-control': 'private',
    'content-length': '53',
    'content-type': 'application/json; charset=utf-8',
    date: 'Thu, 14 Nov 2024 17:13:54 GMT',
    etag: 'W/"35-ejXmOsS85aPypCw7gixnfO0/8dQ"',
    'keep-alive': 'timeout=90',
    'ratelimit-limit': '3000',
    'ratelimit-policy': '3000;w=300',
    'ratelimit-remaining': '2998',
    'ratelimit-reset': '1731604734',
    'strict-transport-security': 'max-age=63072000',
    vary: 'Authorization, Accept-Encoding',
    'x-powered-by': 'Express'
  },
  [cause]: undefined
}

**Comment by aliceisjustplaying** [comment] 2024-11-21 15:04
I saw this with someone else and this was likely caused by the intermittent scaling issues Bluesky currently has. Closing this for now.

**Closed by aliceisjustplaying** 2024-11-21 15:04 UTC
